name: E2E テスト

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  e2e-tests:
    name: E2E テスト実行
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: リポジトリをチェックアウト
      uses: actions/checkout@v4

    - name: Node.js セットアップ
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: 依存関係をインストール
      run: npm ci

    - name: TypeScript型チェック
      run: npm run typecheck

    - name: アプリケーションをビルド
      run: npm run build

    - name: Playwright ブラウザをインストール
      run: npx playwright install --with-deps
      continue-on-error: false

    - name: Playwright バージョン確認
      run: npx playwright --version

    - name: E2E テストを実行
      run: npm test
      env:
        CI: true

    - name: テストレポートをアップロード (成功時)
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: playwright-report-success
        path: playwright-report/
        retention-days: 30

    - name: テストレポートをアップロード (失敗時)
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: playwright-report-failure
        path: playwright-report/
        retention-days: 30

    - name: テスト結果をアップロード
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: test-results/
        retention-days: 30